# Generated by Django 3.2.10 on 2022-06-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_membership_asbl_year'),
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ASBLYear',
        ),
    ]
