# Generated by Django 3.2.10 on 2022-05-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(null=True, upload_to='photo_profil'),
        ),
    ]
