# Generated by Django 3.2.10 on 2022-05-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_photo_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo_profil',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/static/img/pp_defaut.jpg', null=True, upload_to='photo_profil'),
        ),
    ]
