# Generated by Django 3.2.10 on 2022-06-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220602_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='asbl_year',
        ),
    ]
