# Generated by Django 3.2.10 on 2022-05-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
