# Generated by Django 3.2.10 on 2022-05-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_storage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='name',
        ),
    ]
