# Generated by Django 3.2.10 on 2022-05-26 12:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20201012_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='commit',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='commit',
        ),
        migrations.AddField(
            model_name='article',
            name='is_feeding_home_page',
            field=models.BooleanField(default=False, verbose_name="Visible sur la page d'accueil du site"),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default="Aucun résumé n'est disponible pour cet article", verbose_name='Résumé'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='is_feeding_home_page',
            field=models.BooleanField(default=False, verbose_name="Visible sur la page d'accueil du site"),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='summary',
            field=models.TextField(default="Aucun résumé n'est disponible pour cet article", verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('p', 'Projets'), ('m', 'Matériels'), ('e', 'Expérience & conseils'), ('d', 'Divers'), ('h', 'Hackerspace')], max_length=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='category',
            field=models.CharField(choices=[('p', 'Projets'), ('m', 'Matériels'), ('e', 'Expérience & conseils'), ('d', 'Divers'), ('h', 'Hackerspace')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
