# Generated by Django 3.2.10 on 2022-05-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20211004_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('p', 'proposition'), ('i', 'in progress'), ('f', 'finished')], max_length=1, verbose_name='État'),
        ),
    ]
