# Generated by Django 3.2.10 on 2022-05-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_content'),
        ('projects', '0010_alter_comment_content'),
    ]

    operations = [
    ]
