# Generated by Django 3.2.10 on 2022-06-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album'},
        ),
        migrations.AddField(
            model_name='photo',
            name='short_description',
            field=models.CharField(default='description image', max_length=1000, verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.album', verbose_name='Album'),
        ),
    ]
