# Generated by Django 3.2.10 on 2022-06-05 15:48

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_photo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, size=[500, 500], upload_to='gallery_pictures'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='short_description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
