# Generated by Django 3.2.10 on 2022-06-11 15:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20220608_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[500, 500], upload_to='gallery_pictures'),
        ),
    ]
