# Generated by Django 3.2.10 on 2022-05-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_auto_20200807_0242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicOfTheDay',
        ),
    ]
